{
    'name': 'Osoul Occupational Health',
    'version': '1.0.0',
    'category': 'Osoul',
    'summary': 'Osoul Occupational Osoul Health and Safety Management System',
    'author': 'Osoul Information Technology',
    'description': """""",
    'depends': ['base', 'mail', 'hr', 'osoul_human_resources'],
    "data": [
        "data/ir_sequence.xml",
        "data/default.xml",
        "security/ir.model.access.csv",
        "security/security_access_data.xml",
        "reports/osoul_occu_checkup_report.xml",
        "views/osoul_occu_incident.xml",
        "views/osoul_occu_violation.xml",
        "views/osoul_occu_violation_type.xml",
        "views/osoul_occu_site.xml",
        "views/osoul_occu_location.xml",
        "views/osoul_occu_permit.xml",
        "views/osoul_occu_fap.xml",
        "views/osoul_occu_pump.xml",
        "views/osoul_occu_tank.xml",
        "views/osoul_occu_checkup.xml",
        "views/osoul_occu_team.xml",
        "menu/menu.xml",
    ],
    'assets': {
        'web.assets_backend': [
            'osoul_occupational_health/static/src/css/style.css',
            'osoul_occupational_health/static/src/css/kanban.css',
            'osoul_occupational_health/static/src/css/custom_style.scss',
        ],
        'web.assets_frontend': [
            'osoul_occupational_health/static/src/css/custom_style.scss',
        ],
    },
    'demo': [],
    'application': True,
    'installable': True,
    'auto_install': False,
    'sequence': -100,
    'license': 'LGPL-3',
}