{
    'name': 'Osoul Water Delivery Management',
    'version': '1.0.0',
    'category': 'Osoul',
    'summary': 'Water Delivery Management',
    'author': 'Osoul Information Technology',
    'description': """""",
    'depends': ['base', 'mail', 'web', 'hr', 'osoul_human_resources'],
    "data": [
        "security/security_access_data.xml",
        "views/os_vehicle_brand.xml",
        "views/os_water_counter.xml",
        "views/os_water_reception.xml",
        "views/os_water_tanker_entry.xml",
        "views/os_water_contract.xml",
        "views/os_water_vendor.xml",
        "views/os_water_operator.xml",
        "views/os_water_price.xml",
        "data/sequence.xml",
        "menu/menu.xml",
    ],
    'demo': [],
    'application': True,
    'installable': True,
    'auto_install': False,
    'sequence': -100,
    'license': 'LGPL-3',
}
